spring.application.name=bookify

spring.datasource.url=jdbc:mysql://localhost:3306/bookify
spring.datasource.username=${BOOKIFY_DB_USERNAME:root}
spring.datasource.password=${BOOKIFY_DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.cors.allowed-origins=http://localhost:4200
# Obliga a Hibernate a inicializarse en el arranque y no en la primera peticin
spring.jpa.properties.hibernate.defer-datasource-initialization=false
server.servlet.session.timeout=30m

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

cloudinary.cloud-name=nombre_cloud
cloudinary.api-key=api_key
cloudinary.api-secret=api_secret
